# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ef268bd15932ffa1776a86bffe129687c551562090710d4d8a35a12bf5251f2f73131ffa5aac3512495404261cf9d3b141c98fc657a6eec8baa41704fc517a4

test:
  secret_key_base: 3e77d7d967165df58a86239536f4366550a45e6349c651457f86e74a40d82cfe54a7cf0677a2c69a6c0cf77ebe3dda6dd9643332cdbe013b817b7a2cc604c4d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
